### ISSUE TITLE
2023-04-RC1: Add well source terms to the residual separately

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-models#801]
@atgeirr When I run `flow --help` and` flow --help-all` I don't see the `--separate-sparse-source-terms` parameter listed. Should it be?

**Comment by atgeirr** [comment]
The parameter is only seen when running flow_blackoil, not flow. It is therefore not possible to change it when running flow, and the default will always apply (the default is to keep existing behaviour). For now we can experiment with it using flow_blackoil, and if we determine that we want the new behaviour to become the new default we will move it so it will be seen from flow.
